name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
          target
        key: ${{ matrix.os }}

    - name: Test
      run: cargo test --release

    - name: Build
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          cargo build --release --target x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/api-formatter api-formatter-linux-amd64
        fi
      shell: bash

    - name: Archive (Linux)
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@v4
      with:
        name: api-formatter-linux-amd64
        path: api-formatter-linux-amd64
